name 'sssd_ad'
maintainer 'Biola University'
maintainer_email 'jared.king@biola.edu'
license 'apache2'
description 'Installs/Configures SSSD for AD integration'
long_description 'Installs/Configures SSSD for AD integration'
supports 'ubuntu'
version '0.2.0'

depends 'chef-vault', '~> 1.0'
depends 'samba', '~> 0.12'
